import collections
import re

_KNOWN_OPERATION_TYPES = (
    "BATCH.DELETE.OBJECT",
    "REST.COPY.OBJECT",
    "REST.COPY.OBJECT_GET",
    "REST.COPY.PART",
    "REST.DELETE.BUCKET",
    "REST.DELETE.BUCKETPOLICY",
    "REST.DELETE.LIFECYCLE",
    "REST.DELETE.OBJECT",
    "REST.DELETE.OBJECT_TAGGING",
    "REST.DELETE.UPLOAD",
    "REST.GET.ACCELERATE",
    "REST.GET.ACL",
    "REST.GET.ANALYTICS",
    "REST.GET.BUCKET",
    "REST.GET.BUCKETPOLICY",
    "REST.GET.BUCKETVERSIONS",
    "REST.GET.CORS",
    "REST.GET.ENCRYPTION",
    "REST.GET.INTELLIGENT_TIERING",
    "REST.GET.INVENTORY",
    "REST.GET.LIFECYCLE",
    "REST.GET.LOCATION",
    "REST.GET.LOGGING_STATUS",
    "REST.GET.METRICS",
    "REST.GET.NOTIFICATION",
    "REST.GET.OBJECT",
    "REST.GET.OBJECT_LOCK_CONFIGURATION",
    "REST.GET.OBJECT_TAGGING",
    "REST.GET.OWNERSHIP_CONTROLS",
    "REST.GET.PART",
    "REST.GET.POLICY_STATUS",
    "REST.GET.PUBLIC_ACCESS_BLOCK",
    "REST.GET.REPLICATION",
    "REST.GET.REQUEST_PAYMENT",
    "REST.GET.TAGGING",
    "REST.GET.UPLOAD",
    "REST.GET.UPLOADS",
    "REST.GET.VERSIONING",
    "REST.GET.WEBSITE",
    "REST.HEAD.BUCKET",
    "REST.HEAD.BUCKETVERSIONS",
    "REST.HEAD.OBJECT",
    "REST.HEAD.PART",
    "REST.HEAD.UPLOADS",
    "REST.OPTIONS.PREFLIGHT",
    "REST.POST.BUCKET",
    "REST.POST.MULTI_OBJECT_DELETE",
    "REST.POST.OBJECT",
    "REST.POST.UPLOAD",
    "REST.POST.UPLOADS",
    "REST.PUT.ACL",
    "REST.PUT.BUCKET",
    "REST.PUT.BUCKETPOLICY",
    "REST.PUT.CORS",
    "REST.PUT.INVENTORY",
    "REST.PUT.LIFECYCLE",
    "REST.PUT.LOGGING_STATUS",
    "REST.PUT.METRICS",
    "REST.PUT.NOTIFICATION",
    "REST.PUT.OBJECT",
    "REST.PUT.OWNERSHIP_CONTROLS",
    "REST.PUT.PART",
    "REST.PUT.VERSIONING",
    "WEBSITE.GET.OBJECT",
    # "objects;"  # Unsure about this last one; it showed up in a scan of all 7-th string elements
)

_IS_OPERATION_TYPE_KNOWN = collections.defaultdict(bool)
for request_type in _KNOWN_OPERATION_TYPES:
    _IS_OPERATION_TYPE_KNOWN[request_type] = True

_S3_LOG_FIELDS = (
    "bucket_owner",
    "bucket",
    "timestamp",
    "ip_address",
    "requester",
    "request_id",
    "operation",
    "object_key",
    "request_uri",
    # "http_version",  # Regex not splitting this from the request_uri...
    "http_status_code",
    "error_code",
    "bytes_sent",
    "object_size",
    "total_time",
    "turn_around_time",
    "referrer",
    "user_agent",
    "version_id",
    "host_id",
    "signature_version",
    "cipher_suite",
    "authentication_type",
    "host_header",
    "tls_version",
    "access_point_arn",
    "acl_required",
)
_FullLogLine = collections.namedtuple("FullLogLine", _S3_LOG_FIELDS)

_S3_LOG_REGEX = re.compile(pattern=r'"([^"]+)"|\[([^]]+)]|([^ ]+)')

_KNOWN_SERVICES = ("GitHub", "AWS", "GCP", "VPN")  # Azure has problems; see _ip_utils.py for more info

_DEFAULT_REGION_CODES_TO_COORDINATES = {
    # Included for testing/demo purposes
    "AWS/us-east-2": {"latitude": 39.9612, "longitude": -82.9988},
    "GCP/us-central1": {"latitude": 41.2619, "longitude": -95.8608},
    # Explicit entries that fail heuristic matching
    "BO/La Paz Department": {"latitude": -11.7773231, "longitude": -67.4519752},
    "CL/Valparaíso": {"latitude": -32.5976089, "longitude": -70.8529753},
    "CN/Hainan": {"latitude": 19.2000001, "longitude": 109.5999999},
    "CO/Risaralda Department": {"latitude": 5.2102948, "longitude": -75.9842236},
    "CR/San José": {"latitude": 9.9325427, "longitude": -84.0795782},
    "ES/Castille and León": {"latitude": 42.00, "longitude": -5.5},
    "FR/Grand Est": {"latitude": 48.580002, "longitude": 7.750000},
    "IQ/Sulaymaniyah": {"latitude": 35.5574725, "longitude": 45.435202},
    "JP/Ishikawa": {"latitude": 36.9890574, "longitude": 136.8162839},
    "MO/São Francisco Xavier": {"latitude": 22.210928, "longitude": 113.552971},
    "MX/México": {"latitude": 19.4326296, "longitude": -99.1331785},
    "NI/Managua Department": {"latitude": 12.125, "longitude": -86.31},
    "NO/Vestland": {"latitude": 60.9291011, "longitude": 6.1078869},
    "PA/Panamá": {"latitude": 8.559559, "longitude": -81.1308434},
    "PE/Lima Province": {"latitude": -12.5453873, "longitude": -75.8599243},
    "PL/Silesia": {"latitude": 50.6966393, "longitude": 17.9254068},
    "PL/Subcarpathia": {"latitude": 50.0575, "longitude": 22.0896},
    "PR/San Juan": {"latitude": 18.384239, "longitude": -66.05344},
    "RU/Rostov": {"latitude": 57.2012699, "longitude": 39.4221813},
    "TW/Takao": {"latitude": 22.6226696, "longitude": 120.2764261},
    "UY/Montevideo Department": {"latitude": -34.9058916, "longitude": -56.1913095},
    # Skip unknowable entries
    "GitHub": {"latitude": None, "longitude": None},
    "VPN": {"latitude": None, "longitude": None},
    "unknown": {"latitude": None, "longitude": None},
}
